### ISSUE TITLE
DEFAULT_WAIT_DELAY probably too big

### ISSUE THREAD

**Issue by nonmanifold** [axios/moxios#16]
Individual tests are taking too long to complete, and I have to set delay to zero manualy.
Maybe it's better to set this delay to 0 by default?

**Comment by uhoh-itsmaciek** [comment]
+1. Alternately, is there some way to explicitly indicate to moxios that we expect all the requests to have been made instead of using a timeout? Our (default) mocha setup flags all our axios tests as taking too long, because mocha's [slow test threshold](https://mochajs.org/#test-duration) is also around 100ms.

**Comment by uhoh-itsmaciek** [comment]
We ended up dropping moxios because of this. We've moved to mocking our axios calls with [testdouble](https://github.com/testdouble/testdouble.js) using `td.replace` and `td.when` on methods like `axios.get`. It's not as elegant but it's a lot faster.

**Comment by hovissimo** [comment]
Please see https://github.com/axios/moxios/pull/48

**Comment by mzabriskie** [comment]
Fixed with #48
