### ISSUE TITLE
Default moxios import doesn't work in TypeScript

### ISSUE THREAD

**Issue by rossenassenov** [axios/moxios#27]
I tried using https://www.npmjs.com/package/@types/moxios in TypeScript:

```
import moxios from 'moxios';

describe('MoxiosTest', () => {

    beforeEach(() => {console.log(moxios); moxios.install();});
    afterEach(() => moxios.uninstall());

    it('test', () => {
        console.log(moxios);
    });
});
```

and getting error:

```
TypeError: Cannot read property 'install' of undefined
	    at Context.<anonymous> (webpack:///src/api/testing1.test.js:5:75 <- src/api/testing1.test.js:1926:53)
```

I think the problem is how moxios gets exported from moxios.js.

I had to modify:
```
	exports.default = moxios;
	module.exports = exports['default'];
```

to

```
	module.exports = moxios;
	module.exports.default = moxios;
```

in order to get the default import to work.

This is similar to how axios is exported in axios.js:

```
module.exports = axios;

// Allow use of default import syntax in TypeScript
module.exports.default = axios;
```

**Comment by flushentitypacket** [comment]
I think this is technically an issue with the @types/moxios package, since [it types for exports.default](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fa20510b221e0d506cf4edb5bdc3aaf54b42e4ce/types/moxios/index.d.ts#L192) when [moxios assigns to exports](https://github.com/mzabriskie/moxios/blob/62101e4a7c49fbf5b639ed5d36587f2b4941c6a2/dist/moxios.js#L3).

I do think that this is a good change to allow support for both, though.

**Comment by flushentitypacket** [comment]
I sent in a PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16913

**Comment by drouhard** [comment]
The PR got merged, so this Issue can be closed. Thanks for your help, @flushentitypacket. Awesome to see this great library get nurtured.

**Comment by gynet** [comment]
still not working with 0.4.8
TypeError: Cannot read property 'install' of undefined

**Comment by gynet** [comment]
Guys, here is my current workaround, 

import * as moxios from "moxios";

**Comment by anilanar** [comment]
Kamino cloned this issue to anilanar/moxios
